SELECT log.`login_system_login_attempts_first_date` AS 'applied_date',
       a.`application_id`,
       a.`f_name`,
       a.`l_name`,
       a.`m_name`,
       a.`email_id`,
       a.`application_status`,
       p.`user_dob`,
       p.`age`,
       p.`gender`,
       p.`blood_group`,
       p.`hear_abt_csb`,
       p.`hear_abt_csb_others`,
       c.`email_id`,
       c.`mobile_number`,
       c.`phone_number`,
       c.`current_address_line1`,
       c.`current_address_line2`,
       c.`current_address_line3`,
       c.`current_address_city`,
       c.`current_address_state`,
       c.`current_address_state_other`,
       c.`current_address_country`,
       c.`current_address_pin`,
       c.`permanent_same_as_current_address`,
       c.`permanent_address_line1`,
       c.`permanent_address_line2`,
       c.`permanent_address_line3`,
       c.`permanent_address_city`,
       c.`permanent_address_state`,
       c.`permanent_address_state_other`,
       c.`permanent_address_country`,
       c.`permanent_address_pin`,
       c.`parent_name`,
       c.`parent_mobile`,
       c.`parent_relation`,
       c.`parent_organisation`,
       c.`parent_designation`,
       c.`parent_qualification`,
       ex.`exam_score`,
       r.`title_of_refree`,
       r.`name_of_refree`,
       r.`organization`,
       r.`designation`,
       r.`phone_number`,
       r.`email_id`,
       r.`capacity_of_knowing`,
       doc.`passport_photo`,
       doc.`resume`,
       info.`after_mba_plan`,
       ad.`last_update_date`
FROM `admission_users` a
LEFT JOIN `login_system_login_attempts` log ON a.application_id = log.login_system_login_attempts_username
LEFT JOIN `admission_section_status` ad ON a.application_id = ad.application_id
LEFT JOIN `users_personal_details` p ON a.application_id = p.application_id
LEFT JOIN `users_contact_details` c ON a.application_id = c.application_id
LEFT JOIN `user_exam_score` ex ON a.application_id = ex.application_id
LEFT JOIN `users_reference_details` r ON a.application_id = r.application_id
LEFT JOIN `users_documents_uploads` doc ON a.application_id = doc.application_id
LEFT JOIN `user_additional_info` info ON a.application_id = info.application_id